var x = 10;
var y = 20;
var z = true;
var myName = "Kanwal";
var fruits = ["Apple", "Mango", "Banana"];
console.log("1. x > y (I predict False) => ".concat(x > y));
console.log("2. x <= y (I predict True) => ".concat(x <= y));
console.log("3. x == y (I predict False) => ".concat(x == y));
console.log("4. !z (I predict False) => ".concat(!z));
console.log("5. name == \"Kanwal\" (I predict True) => ".concat(myName == "Kanwal"));
console.log("6. fruits.length > 0 (I predict True) => ".concat(fruits.length > 0));
console.log("7. fruits.length === 0 (I predict False) => ".concat(fruits.length === 0));
console.log("8. name != \"Kanwal\" (I predict False) => ".concat(myName != "Kanwal"));
console.log("9. x < y (I predict True) => ".concat(x < y));
console.log("10. x != y (I predict True) => ".concat(x != y));
